/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 public/models/Final-Room-baked.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Final-Room-baked.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Houseplant_1" position={[-1.19, 0.017, -1.326]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh name="Houseplant_1_1" geometry={nodes.Houseplant_1_1.geometry} material={materials.Black} />
        <mesh name="Houseplant_1_2" geometry={nodes.Houseplant_1_2.geometry} material={materials.Brown} />
        <mesh name="Houseplant_1_3" geometry={nodes.Houseplant_1_3.geometry} material={materials.Plant_Green} />
      </group>
      <group name="table" position={[0.259, 0.008, -1.213]} rotation={[0, -1.571, 0]}>
        <mesh name="Plane001_Plane002_BlackWood" geometry={nodes.Plane001_Plane002_BlackWood.geometry} material={materials.BlackWood} />
        <mesh name="Plane001_Plane002_BlackWood_1" geometry={nodes.Plane001_Plane002_BlackWood_1.geometry} material={materials.GrayPlastic} />
        <mesh name="Plane001_Plane002_BlackWood_2" geometry={nodes.Plane001_Plane002_BlackWood_2.geometry} material={materials.BlackCoatSteel} />
        <mesh name="Plane001_Plane002_BlackWood_3" geometry={nodes.Plane001_Plane002_BlackWood_3.geometry} material={materials.WhiteSteelScrew} />
        <mesh name="Plane001_Plane002_BlackWood_4" geometry={nodes.Plane001_Plane002_BlackWood_4.geometry} material={materials.BlackPlastic} />
      </group>
      <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={materials['Mat.001']} position={[0.191, 0.956, -1.017]} scale={0.007} />
      <mesh name="Mousepad" geometry={nodes.Mousepad.geometry} material={materials.Mousepad} position={[0.711, 0.967, -0.951]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.504, 12.787, 0.139]} />
      <mesh name="ComputerMouse_mesh" geometry={nodes.ComputerMouse_mesh.geometry} material={materials.ComputerMouse_mat1} position={[0.719, 0.955, -0.957]} rotation={[Math.PI, 0, Math.PI]} scale={0.031} />
      <group name="Phone" position={[1.014, 0.955, -0.914]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
        <mesh name="Phone_01_Cube037-Mesh" geometry={nodes['Phone_01_Cube037-Mesh'].geometry} material={materials['1A1A1A']} />
        <mesh name="Phone_01_Cube037-Mesh_1" geometry={nodes['Phone_01_Cube037-Mesh_1'].geometry} material={materials['039BE5']} />
        <mesh name="Phone_01_Cube037-Mesh_2" geometry={nodes['Phone_01_Cube037-Mesh_2'].geometry} material={materials.F44336} />
      </group>
      <group name="Small_Plant" position={[0.991, 1.14, -1.443]} scale={0.521}>
        <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.mat22} />
        <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat9} />
        <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat20} />
      </group>
      <group name="Chair" position={[0.194, 0.382, -0.326]} rotation={[Math.PI, 0, Math.PI]} scale={0.035}>
        <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials['Office_Cha.001']} />
        <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials['Office_Cha_1.001']} />
      </group>
      <group name="Mat" position={[0.595, 0, 0.577]} scale={0.742}>
        <mesh name="rugRectangle_3" geometry={nodes.rugRectangle_3.geometry} material={materials.carpetDarker} />
        <mesh name="rugRectangle_3_1" geometry={nodes.rugRectangle_3_1.geometry} material={materials.carpet} />
      </group>
      <group name="Shelf" position={[0.136, 2.166, -1.583]} scale={0.243}>
        <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={materials.lambert2SG} />
        <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={materials.lambert3SG} />
      </group>
      <group name="Lamp" position={[-0.047, 2.355, -1.588]} scale={0.034}>
        <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials.lambert4SG} />
        <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['lambert2SG.001']} />
        <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={materials['lambert3SG.001']} />
      </group>
      <group name="Calendar" position={[0.203, 2.304, -1.547]} scale={0.006}>
        <mesh name="Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1" geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1.geometry} material={materials.Calendar_Aquamarine} />
        <mesh name="Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_1" geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_1.geometry} material={materials.Calendar_Ivory} />
        <mesh name="Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_2" geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_2.geometry} material={materials.Calendar_Texture} />
        <mesh name="Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_3" geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_3.geometry} material={materials.FrontColor} />
      </group>
      <group name="pCube37" position={[0.927, 0.997, -0.617]} scale={0.001}>
        <mesh name="pCube37_1" geometry={nodes.pCube37_1.geometry} material={materials.blinn9SG} />
        <mesh name="pCube37_1_1" geometry={nodes.pCube37_1_1.geometry} material={materials.blinn2SG} />
        <mesh name="pCube37_1_2" geometry={nodes.pCube37_1_2.geometry} material={materials.blinn11SG} />
        <mesh name="pCube37_1_3" geometry={nodes.pCube37_1_3.geometry} material={materials.blinn4SG} />
        <mesh name="pCube37_1_4" geometry={nodes.pCube37_1_4.geometry} material={materials.blinn6SG} />
        <mesh name="pCube37_1_5" geometry={nodes.pCube37_1_5.geometry} material={materials.blinn7SG} />
        <mesh name="pCube37_1_6" geometry={nodes.pCube37_1_6.geometry} material={materials.blinn5SG} />
      </group>
      <group name="screen" position={[0.199, 1.1, -1.322]} rotation={[0, -1.571, 0]}>
        <mesh name="mesh76221598" geometry={nodes.mesh76221598.geometry} material={materials.mat17} />
        <mesh name="mesh76221598_1" geometry={nodes.mesh76221598_1.geometry} material={materials.mat23} />
      </group>
      <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
      <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.Default} />
    </group>
  )
}

useGLTF.preload('/Final-Room-baked.glb')
