/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 public/models/Room-Baked.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei';
import * as THREE from "three";

export function Office(props) {
  const { nodes, materials } = useGLTF('models/my-room.glb')  
  const texture = useTexture("textures/my-bake.001.png")  
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture
  })

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  })


  return (
    <group {...props} dispose={null}>
      <group name="Desk" position={[-0.074, 0, -1.521]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh name="Plane001_Plane002_BlackWood001" geometry={nodes.Plane001_Plane002_BlackWood001.geometry} material={textureMaterial} />
        <mesh name="Plane001_Plane002_BlackWood001_1" geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry} material={textureMaterial} />
        <mesh name="Plane001_Plane002_BlackWood001_2" geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry} material={textureMaterial} />
        <mesh name="Plane001_Plane002_BlackWood001_3" geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry} material={textureMaterial} />
        <mesh name="Plane001_Plane002_BlackWood001_4" geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry} material={textureMaterial} />
      </group>
      <group name="SM_ShelfSM_Shelf1" position={[-0.868, 1.694, -1.953]}>
        <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={textureMaterial} />
        <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={textureMaterial} />
      </group>
      <group name="LavaLamp" position={[-1.302, 2.071, -1.96]}>
        <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={textureMaterial} />
      </group>
      <mesh name="WawaRug" geometry={nodes.WawaRug.geometry} material={textureMaterial} position={[-0.281, 0.009, 0.765]} />
      <group name="keyboard" position={[-0.044, 0.981, -1.346]} rotation={[-0.014, -0.246, -0.049]}>
        <mesh name="mesh425587018" geometry={nodes.mesh425587018.geometry} material={textureMaterial} />
        <mesh name="mesh425587018_1" geometry={nodes.mesh425587018_1.geometry} material={textureMaterial} />
        <mesh name="mesh425587018_2" geometry={nodes.mesh425587018_2.geometry} material={textureMaterial} />
        <mesh name="mesh425587018_3" geometry={nodes.mesh425587018_3.geometry} material={textureMaterial} />
      </group>
      <group name="iMac" position={[0.454, 0.939, -1.723]} rotation={[Math.PI, -1.099, Math.PI]}>
        <mesh name="iMac_1" geometry={nodes.iMac_1.geometry} material={textureMaterial} />
        <mesh name="iMac_1_1" geometry={nodes.iMac_1_1.geometry} material={textureMaterial} />
        <mesh name="iMac_1_2" geometry={nodes.iMac_1_2.geometry} material={textureMaterial} />
      </group>
      <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={textureMaterial} position={[-0.108, 0, 0.183]} />
      <group name="plant" position={[-0.78, 1.071, -1.61]}>
        <mesh name="mesh24448074" geometry={nodes.mesh24448074.geometry} material={textureMaterial} />
        <mesh name="mesh24448074_1" geometry={nodes.mesh24448074_1.geometry} material={textureMaterial} />
        <mesh name="mesh24448074_2" geometry={nodes.mesh24448074_2.geometry} material={textureMaterial} />
      </group>
      <group name="Houseplant_7" position={[-2.019, 0.021, -1.526]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Houseplant_7_1" geometry={nodes.Houseplant_7_1.geometry} material={textureMaterial} />
        <mesh name="Houseplant_7_2" geometry={nodes.Houseplant_7_2.geometry} material={textureMaterial} />
        <mesh name="Houseplant_7_3" geometry={nodes.Houseplant_7_3.geometry} material={textureMaterial} />
      </group>
      <group name="Chair" position={[-0.278, 0, -0.708]} rotation={[0, -0.376, 0]}>
        <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
      </group>
      <group name="Phone_01_Cube037" position={[0.656, 0.94, -1.133]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
        <mesh name="Phone_01_Cube037-Mesh" geometry={nodes['Phone_01_Cube037-Mesh'].geometry} material={textureMaterial} />
        <mesh name="Phone_01_Cube037-Mesh_1" geometry={nodes['Phone_01_Cube037-Mesh_1'].geometry} material={textureMaterial} />
        <mesh name="Phone_01_Cube037-Mesh_2" geometry={nodes['Phone_01_Cube037-Mesh_2'].geometry} material={textureMaterial} />
      </group>
      <group name="Calendar" position={[-0.681, 1.983, -1.889]} scale={0.015}>
        <mesh name="Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1" geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1.geometry} material={textureMaterial} />
        <mesh name="Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_1" geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_1.geometry} material={textureMaterial} />
        <mesh name="Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_2" geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_2.geometry} material={textureMaterial} />
        <mesh name="Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_3" geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model_1_3.geometry} material={textureMaterial} />
      </group>
      <group name="Node" position={[1.367, 2.432, -2.172]} rotation={[3.127, -0.003, -1.571]} scale={1.828}>
        <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh002_3" geometry={nodes['Node-Mesh002_3'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh002_4" geometry={nodes['Node-Mesh002_4'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh002_5" geometry={nodes['Node-Mesh002_5'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh002_6" geometry={nodes['Node-Mesh002_6'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh002_7" geometry={nodes['Node-Mesh002_7'].geometry} material={textureMaterial} />
      </group>
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={textureMaterial} />
      <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={textureMaterial} />
      <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={textureMaterial} />
      <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={textureGlassMaterial} />
    </group>
  )
}

useGLTF.preload('models/sceen.glb')
